### PR TITLE
Automated cherry pick of #37: Fix semaphore org / id for this project

### PR DESCRIPTION
**Pull request by Brian-McM**
Cherry pick of #37 on release-calient-v3.9.

#37: Fix semaphore org / id for this project

### CODE REVIEW

**Review by doublek — APPROVED** [review]
LGTM

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
